### ISSUE TITLE
Social API doc?

### ISSUE THREAD

**Issue by ttback** [SocialFlowDev/socialflow-api-example#1]
I have been looking everywhere and can't find anything about SocialFlow api doc on scheduling tweet with/without image.

**Comment by antipasta** [comment]
Hi,

Our api doc has a section entitled 'Attach an image to a message'. If your copy of the documentation does not have this, please contact your account manager, or SocialFlow support, and we can get an updated copy sent out to you, or help with any dev issues you're running into.

**Comment by ttback** [comment]
@antipasta Thanks for replying. A side question, do you know if SocialFlow compose view has a separate direct link? With possibility to pre-populate fields with GET parameters?

**Comment by antipasta** [comment]
Currently there is no way to get a direct link to just the compose box, since compose is tightly integrated with our current publish page. That is a good idea though, and is something I will pass up the chain as something we should consider when thinking about changes to our compose functionality

**Comment by ttback** [comment]
@antipasta It would be good to have. We have a use case that we want to use a socialflow compose url with parameters so we can repost some of the past popular tweets. But there doesn't seem to be an easy way to do that with SocialFlow at the moment.
